### ISSUE TITLE
Review InCommon Research & Scholarship Schema for VEDA User Profile

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#12]
### Description
The InCommon Research & Scholarship (R&S) entity category defines a streamlined approach for federated research access. Identity providers (IDP) supporting R&S releases, pre-defined information to service providers (SP).

As part of integrating with the Veda Auth Central portal, we need to confirm a solid and standardized user profile. This task reviews the R&S schema to confirm a solid, standardized  VEDA user profile

### Tasks
- [ ] Understand R&S Attributes
   - Explore the R&S schema and documentation.
   - Identify attributes commonly used for research and scholarly purposes.

- [ ] Map R&S Attributes to VEDA user profile
   - Collaborate with VEDA app admins to determine which R&S attributes align with VEDA app requirements.
   - Document the mapping of attributes to specific apps.

- [ ] Privacy Considerations
   - Ensure compliance with privacy regulations.
   - Discuss any sensitive attributes and their handling.

**Comment by lahirujayathilake** [comment]
Closing this as we've already come up with the attributes. However, based on the VEDA App requirements additions/modifications will occur
