### ISSUE TITLE
GitHub document for VEDA Auth use cases

### ISSUE THREAD

**Issue by lahirujayathilake** [NASA-IMPACT/veda-auth-central#120]
For better maintenance and to keep track, move the use cases defined in https://docs.google.com/document/d/1vwqLwVSZH6ZbofWFcLC9CDVueynoVHHHCPdZLK0n1J8/edit?tab=t.0#heading=h.2impdml7o5bv to GitHub documents

**Comment by j08lue** [comment]
We agreed today that we would put the actual auth use case descriptions into one issue per use case, so they get a unique ID and reference (the ticket number and URL) and we can refine them individually.

We can perhaps persist them in Markdown docs or somewhere, once refinement is complete.

**Comment by j08lue** [comment]
Done in these issues: https://github.com/NASA-IMPACT/veda-auth-central/issues?q=is%3Aissue+is%3Aopen+label%3A%22use+case%22
