### ISSUE TITLE
Need test server running on HTTPS

### ISSUE THREAD

**Issue by alukach** [NASA-IMPACT/veda-auth-central#58]
We're attempting to do some early integration with Grafana, utilizing VEDA Auth Central as an OAuth2 Provider.  However, we're not aware of any services running on HTTPS.

Known servers to date:

* http://3.147.103.56:8081/swagger-ui/index.html
* http://18.191.42.248:8081/swagger-ui/index.html

as an aside, I'm not sure what the difference is between these instances.

---

Relates to https://github.com/NASA-IMPACT/veda-backend/issues/373

**Comment by lahirujayathilake** [comment]
This has already been addressed and test server is running on HTTPS
