### ISSUE TITLE
Auth Central integration with Grafana

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-auth-central#61]
We deployed a Grafana instance using genetic OAuth settings in [veda-monitoring](https://github.com/NASA-IMPACT/veda-monitoring/blob/feature/keycloak/stacks/grafana.py#L371) using the following endpoints:

http://18.191.42.248:8081/api/v1/identity-management/authorize
http://18.191.42.248:8081/api/v1/identity-management/token
http://18.191.42.248:8081/api/v1/identity-management/user

Here is the Grafana link: https://d1z1g2cnqbz2id.cloudfront.net

We're receiving an `Unexpected error occurred` error when attempting to login.

**Comment by lahirujayathilake** [comment]
@smohiudd, could you please share the error log?

**Comment by alukach** [comment]
I logged this in #60

**Comment by smohiudd** [comment]
Sure thing, I'll close this one
