### ISSUE TITLE
Objective AU-1: Assist VEDA app integrations with VEDA Auth Central to streamlined authentication.

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#62]
## Motivation

In this PI, VEDA systems are transitioning to a centralized authentication model. Specifically, authentication processes will be handled through the newly implemented VEDA Auth Central system. As part of our focus during this PI, we are actively integrating and rigorously testing VEDA Auth Central with all VEDA applications. This strategic move aims to streamline authentication transactions across the entire VEDA ecosystem, enhancing security and user experience.

## Team & Owner(s)*

Lahiru*, Suresh, Eroma, Anthony L, Alex, Sanjay, Saadiq, Alexandra

## Success Criteria 

- Identified VEDA Apps (STAC, VEDAHub, Dashboard) are integrated, tested, and ready for production launch.

```[tasklist]
### Tasks
- [x] Integrate VEDA STAC with Auth Central
- [x] VEDA Grafana Integration with Auth Central
```

### Stretch goals:
One or more VEDA Apps identified above successfully using VEDA Auth Central at the production level.

## Risks/Dependencies

- Planning cross-team tasks and aligning the sprint to work together. 
- Since this is the initial effort with Auth Central integration, the level of effort on issue fixes, retesting, etc could take longer than expected.

**Comment by lahirujayathilake** [comment]
Grafana integration was addressed in,

* https://github.com/NASA-IMPACT/veda-auth-central/issues/65
* https://github.com/NASA-IMPACT/veda-auth-central/issues/66

**Comment by eroma2014** [comment]
The planned AU objective is on pause due the ADR review process. The VEDA teams are in discussion.
ADR documentation
1. [Adding a Custom Layer on Top of Keycloak for Veda Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture-decision-records/layering-on-keycloak.md)
2. [Authentication in VEDA Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture/1-veda-authn-flow.md)
3. [Authorization in VEDA Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture/2-veda-authz-flow.md)
4. [Application-Specific Administration in Veda Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture/3-vac-app-admin.md)
5. [A Customs User Portal for VEDA Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/auth-user-portal/docs/architecture-decision-records/custom-user-portal.md)

ADR discussion
1. https://github.com/NASA-IMPACT/veda-auth-central/discussions/85
2. https://github.com/NASA-IMPACT/veda-auth-central/pull/87

**Comment by eroma2014** [comment]
Closing this objective as all tasks are completed
