### ISSUE TITLE
Bug: Requirement of client_id in OpenID Provider Configuration Information URL violates spec

### ISSUE THREAD

**Issue by alukach** [NASA-IMPACT/veda-auth-central#78]
Currently, to retrieve the OpenID Provider Configuration Information, a user must provide a client ID as a query parameter (e.g. https://api.veda.usecustos.org/api/v1/identity-management/.well-known/openid-configuration?client_id=veda-iui65nmkgaf7bihdyndc-10000000).

The [OpenID Connect Discovery spec](https://openid.net/specs/openid-connect-discovery-1_0-final.html#ProviderConfig) states:

> OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by concatenating the string `/.well-known/openid-configuration` to the Issuer.

By requiring a ClientID to be provided, we violate the above requirement.

As a demonstration of how this seemingly innocuous detail can affect greater systems, consider a tool like [`oidc-client-ts`](https://github.com/authts/oidc-client-ts). This automatically builds the OIDC Configuration URL based on the provided Issuer:

https://github.com/authts/oidc-client-ts/blob/8181652f609242dd14ee1ae4f6b82a9a5116f966/src/OidcClientSettings.ts#L256-L261

Tools like Radiant Earth's STAC Browser build upon this library:

https://github.com/radiantearth/stac-browser/blob/8780e95dd359e67398664ddf6e99628f8c79de7c/src/auth/oidc.js#L12-L19

As such, the Radiant Earth STAC Browser is currently incompatible with VEDA Auth Central.

---

/cc @lahirujayathilake

**Comment by alukach** [comment]
Closed by 5ced43e6c35a0483aebe7d054761dffac507adae

**Comment by lahirujayathilake** [comment]
Fixed with - https://github.com/NASA-IMPACT/veda-auth-central/pull/98
