### ISSUE TITLE
Optimize Group Management Endpoints for Admin Portal Integration

### ISSUE THREAD

**Issue by lahirujayathilake** [NASA-IMPACT/veda-auth-central#83]
Update the group management endpoints to align with the requirements of the admin portal. The current design necessitates multiple requests to gather necessary data for the UI. By modifying the endpoints or adding new ones, we aim to consolidate these requests, improving efficiency and reducing the number of API calls

**Comment by lahirujayathilake** [comment]
This is in progress
* https://github.com/NASA-IMPACT/veda-auth-central/pull/92

**Comment by eroma2014** [comment]
Closing the issue for now, in the future, if there are any new requirements from the VEDA Auth Central portal while it's in development, we will open this.
